#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#


"""

Programa para gestão do combate

Usage:
    siur-img set [ <filename> ]

Options:
    --version

"""

import os

from docopt import docopt
from modules.siur_pastas_de_dados import pasta_imagens, pasta_raiz
from modules.siur_imagens import select_img
from modules.siur_arquivos_alvo import target_character_img
from modules.cli_tools import create_target_file

args = docopt(__doc__)

def main():
    if args['set']:
        if args['<filename>']:
            selected_img = args['<filename>']
        else:
            selected_img = select_img(pasta_imagens)

        create_target_file(selected_img, target_character_img, file_folder=pasta_imagens, target_folder=pasta_raiz)





if __name__ == '__main__':
    main()
